pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('frontend-interview-scheduler') { // Navigate to the correct subdirectory
                    sh 'npm install'
                }
            }
        }

        stage('Build') {
            steps {
                dir('frontend-interview-scheduler') { // Ensure the build runs in the correct directory
                    sh 'npm run build'
                }
            }
        }

        stage('Deploy') {
    steps {
        sh '''
        sudo mkdir -p /var/www/interview-scheduler-frontend
        sudo cp -R frontend-interview-scheduler/dist/interview-scheduler/* /var/www/interview-scheduler-frontend/
        '''
    }
}

    }

    post {
        success {
            echo 'Frontend build and deployment succeeded!'
        }
        failure {
            echo 'Frontend build or deployment failed.'
        }
    }
}
