pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                checkout scm
                dir('frontend-interview-scheduler') {
                    echo "Switching to frontend subdirectory"
                }
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('Build') {
            steps {
                sh 'npm run build'
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                mkdir -p /var/www/interview-scheduler-frontend
                cp -R build/* /var/www/interview-scheduler-frontend/
                '''
            }
        }
    }

    post {
        success {
            echo 'Frontend build and deployment succeeded!'
        }
        failure {
            echo 'Frontend build or deployment failed.'
        }
    }
}
